### ISSUE TITLE
ImportError: No module named 'winrandom'

### ISSUE THREAD

**Issue by ghost** [pycrypto/pycrypto#110]
I tried 3 approaches:
a) Binary build v2.6.1
b) `pip install pycrypto`
c) manual install v2.7a1

```
C:\Python34\pycrypto-2.7a1>c:\Python34\python.exe setup.py build
running build
running build_py
running build_ext
warning: GMP or MPIR library not found; Not building Crypto.PublicKey._fastmath.


Second pass to allow 2to3 to fix nt.py. No cause for alarm.

running build
running build_py
copying lib\Crypto\Random\OSRNG\nt.py -> build\lib.win32-3.4\Crypto\Random\OSRNG

Skipping implicit fixer: buffer
Skipping implicit fixer: idioms
Skipping implicit fixer: set_literal
Skipping implicit fixer: ws_comma
running build_ext
warning: GMP or MPIR library not found; Not building Crypto.PublicKey._fastmath.
```

All give the same error, namely that `winrandom` is missing. 
I tried to build `windrandom` (https://pypi.python.org/pypi/winrandom/1.2) as well (also builds fine, but I still get the same error about it missing.

```
C:\Python34\winrandom-1.2\winrandom-1.2>python counterpartyd\counterparty-cli.py --help
Traceback (most recent call last):
  File "c:\counterpartyd_build\dist\counterpartyd\counterparty-cli.py", line 14,
 in <module>
    from Crypto.PublicKey import RSA
  File "C:\Python34\lib\site-packages\Crypto\PublicKey\RSA.py", line 78, in <mod
ule>
    from Crypto import Random
  File "C:\Python34\lib\site-packages\Crypto\Random\__init__.py", line 28, in <m
odule>
    from Crypto.Random import OSRNG
  File "C:\Python34\lib\site-packages\Crypto\Random\OSRNG\__init__.py", line 34,
 in <module>
    from Crypto.Random.OSRNG.nt import new
  File "C:\Python34\lib\site-packages\Crypto\Random\OSRNG\nt.py", line 28, in <m
odule>
    import winrandom
ImportError: No module named 'winrandom'

C:\Python34\winrandom-1.2\winrandom-1.2>python -V
Python 3.4.2

```

I'm not sure if I'm missing something obvious here?

**Comment by rippler** [comment]
Installed Python 3.4.2 and all modules from scratch (`pycrypto` using `pip`) on Windows 8.1 x86 and I'm still having the same problem. Above I observed on Windows 7 x64.

**Comment by icoxfog417** [comment]
Did you try [python3-pycrypto-windows-installer](https://github.com/axper/python3-pycrypto-windows-installer)? It will be helpful.

**Comment by rippler** [comment]
@icoxfog417 no, I wasn't aware of it. I bookmarked the link.

**Comment by espdev** [comment]
@icoxfog417, this installer does not have `_fastmath` extension. (See also http://xpra.org/trac/ticket/373)

**Comment by costypetrisor** [comment]
I've ran into the same issue recently as well.
But since my context needed `pip install pycrypto` to work, I looked at possible fixes and found that merging PR #116 would fix this too.

**Comment by neRok-** [comment]
I am having this problem with python 3.4 on win 7 x64. Everything was installed to a virtualenv using pip (so should be working).

I found a hacky fix here: https://stackoverflow.com/questions/24804829/another-one-about-pycrypto-and-paramiko



> Problem is solved by editing string in crypto\Random\OSRNG\nt.py:
>    `import winrandom`
> to
>    `from . import winrandom`

**Comment by tsingroo** [comment]
thanks fro @icoxfog417  ,python3-pycrypto-windows-installer fixed my issue.

**Comment by jakirkham** [comment]
I believe this PR ( https://github.com/dlitz/pycrypto/pull/46 ) fixed the Python 3.x import error cited by @neRok- above.

**Comment by pravic** [comment]
PR #46 fixed, but PyPi contains the old version still.

**Comment by NuclearManD** [comment]
This is a problem for me. It really needs to be fixed.  Although many people use Linux, most people use Windows, which pycrypto is quite unstable on.  I used pypi to install it, will try other windows installer.

**Comment by jakirkham** [comment]
AFAICT `pycrypto` is unmaintained. Would recommend looking at `pycryptodome`, which provides a very similar interface.

**Comment by NuclearManD** [comment]
Unfortunately I am using the coinbase API, which relies on pycrypto...  But I fixed it.  python3-pycrypto-windows-installer is a fix.
