### ISSUE TITLE
time.clock is deprecated - python 3.7

### ISSUE THREAD

**Issue by ErwinHaasnoot** [pycrypto/pycrypto#283]
When using RSA encrypt with PKCS1_AOEP padding, DeprecationWarnings are thrown. 

Prerequisites: an RSA private key in mykey.pem

```openssl genrsa -out mykey.pem 1024```

Run the following with the "-W error" option to trigger the warning and print stacktrace:

```
import os
from Crypto.PublicKey import RSA
from Crypto.Cipher import PKCS1_OAEP
from Crypto.Hash import SHA
with open('rsa.key') as f: key = f.read()
rsa_key = RSA.importKey(key)
rsa = PKCS1_OAEP.new(rsa_key, SHA)
encdata = rsa.encrypt(data)
```

```
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    encdata = rsa.encrypt(data)
  File "/usr/local/lib/python3.7/site-packages/Crypto/Cipher/PKCS1_OAEP.py", line 152, in encrypt
    ros = randFunc(hLen)
  File "/usr/local/lib/python3.7/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 202, in read
    return self._singleton.read(bytes)
  File "/usr/local/lib/python3.7/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 178, in read
    return _UserFriendlyRNG.read(self, bytes)
  File "/usr/local/lib/python3.7/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 129, in read
    self._ec.collect()
  File "/usr/local/lib/python3.7/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 77, in collect
    t = time.clock()
DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead```

**Comment by tirkarthi** [comment]
`time.clock` is now removed in 3.8 : https://github.com/python/cpython/pull/13270/

**Comment by rhanka** [comment]
python 3.8 is now the official 3 for docker images

This problem has then to be solved for most people who will use python 3 with docker.

We have the problem, as we use a docker container for encrypting fake data in our travis process (https://github.com/histovec/histovec-beta/). Even if the resource is not critical for our project, is would seem hygienic to solve this 

```
...
    iv = Random.new.read(AES.bloc_ksize)
  File "/usr/local/lib/python3.7/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 202, in read
    return self._singleton.read(bytes)
  File "/usr/local/lib/python3.7/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 178, in read
    return _UserFriendlyRNG.read(self, bytes)
  File "/usr/local/lib/python3.7/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 129, in read
    self._ec.collect()
  File "/usr/local/lib/python3.7/site-packages/Crypto/Random/_UserFriendlyRNG.py", line 77, in collect
    t = time.clock()
DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
```

Users of the Crytpo lib with docker must now downgrade using a `FROM python:3.7-slim` (or `FROM python:3.7`) instead of `FROM python:3-slim` (or `FROM python:3`) in their `Dockerfile`, at least until the problem has been fixed and close here.

**Comment by ErwinHaasnoot** [comment]
Thanks. Please note that this library has been deprecated and one should
switch to pycryptodome for an API-compatible, updated lib, or to
cryptography.io for a more modern API.

**Comment by rhanka** [comment]
Thank your for your response - this explanation is profitable !

**Comment by cs01** [comment]
@ErwinHaasnoot if this library is deprecated, could it be marked as such on PyPI, GitHub and other relevant pages? It is not clear when stumbling across the project from search results. I luckily found it when running into this Python 3.8 incompatibility.

**Comment by ErwinHaasnoot** [comment]
That would be great. Unfortunately I don't have commit rights; maybe a
merge request would be accepted if sent.

**Comment by ThanhTuNguyen** [comment]
Please fix this bug, downgrade to 3.7 is not the acceptable solution

**Comment by SwapnilSoni1999** [comment]
2020 and still no fixed yet

**Comment by michael-k** [comment]
@SwapnilSoni1999 see above:

> Please note that this library has been deprecated and one should
switch to pycryptodome for an API-compatible, updated lib, or to
cryptography.io for a more modern API.

**Comment by SwapnilSoni1999** [comment]
Okay thanks tho <3
I would suggest to archive or add deprecated tag/text on title description

**Comment by cs01** [comment]
Good idea https://github.com/pycrypto/pycrypto/issues/283#issuecomment-583685466

**Comment by whitespots** [comment]
+1 to waiters

**Comment by dingyaguang117** [comment]
Please try this polyfill

 `time.clock = time.process_time`

**Comment by AyliD** [comment]
+1 for waiter

**Comment by Pitastic** [comment]
+1 for waiter

**Comment by cygnusb** [comment]
+1

**Comment by jfunction** [comment]
waiter++

**Comment by jfunction** [comment]
waiter-- 
I switched to `pycryptodome` and that worked for me.
