### ISSUE TITLE
SyntaxError: invalid syntax on installation of PyCrypto

### ISSUE THREAD

**Issue by to175** [pycrypto/pycrypto#317]
Hello,

When I installed PyCrypto I got this error : SyntaxError: invalid syntax.

```
C:\Users\user>pip install PyCrypto==2.3
Collecting PyCrypto==2.3
  Downloading pycrypto-2.3.tar.gz (331 kB)
     |████████████████████████████████| 331 kB 437 kB/s
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\user\Documents\WPy64-3850\python-3.8.5.amd64\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-jjc3z61m\\pycrypto\\setup.py'"'"'; __file__='"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-jjc3z61m\\pycrypto\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\user\AppData\Local\Temp\pip-pip-egg-info-_0kfoqhk'
         cwd: C:\Users\user\AppData\Local\Temp\pip-install-jjc3z61m\pycrypto\
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\user\AppData\Local\Temp\pip-install-jjc3z61m\pycrypto\setup.py", line 46
        raise RuntimeError, ("The Python Cryptography Toolkit requires "
                          ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by aminsoheyli** [comment]
This project is  dead! #173 

Use [pycryptodome](https://github.com/Legrandin/pycryptodome) or [cryptography](https://github.com/pyca/cryptography).

**Comment by Yilmaz4** [comment]
> 
> 
> This project is dead! #173
> 
> Use [pycryptodome](https://github.com/Legrandin/pycryptodome) or [cryptography](https://github.com/pyca/cryptography).

I understand it's dead, but can you explain why? In my PC, it gives error status 2 with cl.exe. Is newer versions of visual studio build tools is incompatible with pycrypto?

**Comment by zbentley** [comment]
@Yilmaz4 I think this is the same issue as #327; try the workaround linked [here](https://github.com/pycrypto/pycrypto/issues/327#issuecomment-1002320016).
