### ISSUE TITLE
publickey().exportKey(format="OpenSSH") failing on python 3.4

### ISSUE THREAD

**Issue by Itxaka** [pycrypto/pycrypto#99]
On MacOSX 10.10
Python 3.4.2 installed from brew
pycrypto installed from pip
$ pip3 list|grep crypto
pycrypto (2.6.1)

```
>>> import Crypto
>>> Crypto.__version__
'2.6.1'
>>> key = Crypto.PublicKey.RSA.generate(4096)
>>> key
<_RSAobj @0x105c5a160 n(4096),e,d,p,q,u,private>
>>> key.publickey()
<_RSAobj @0x105c6afd0 n(4096),e>
>>> key.publickey().exportKey()
b'-----BEGIN PUBLIC KEY-----\nMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAyzwzfoNoYJHGOhDEtu/j\naxDVdF0yzINOWuAQzfgz0Jwu3uXgMX3X/u/DmddiR6Fi0VTZuoCz3UWyXEUYSHVQ\niE2/p68n319lLcVqX3x5pJzjnQwKndVec6JjhB7rNCauBCzenDIH8hKVN7ce4n84\nG6TjqeGUXmDNY+FspG1KPklGBkDwv9iJZeiMvtl73pmbaX0k6JpQrP+Ff30pzD6Q\n7xnWniSEjniFu/zLymjs6a9SWulbOMso0l4rT6mPHiQ4Ed88KsvWZ6Jcu5d5drld\nkdHJt/+ajTUce2kbjZzXjewKdnGFOB+/4f4FQX/N7Naca1nvw241+LAnzMjxyfOu\nEd8BoGhH30zkxjXDsDCCwH+YPcoO5QgiZd7QF91Msu7vFqbkHtfMvUrhAjzPpz8n\ntYRc6eAHSTPgnsQGyiTp8ySqhtCOIk2klYpcOPmtHBEgzi8ktLMXRSUtMiRGeo3v\n5ilreVtVlKS6KIpJLsjzVtLj5PiXPOokOsCCKunBe6RBcUMVrWwrKdKOKJsQblie\nYxX5Dk8W/ioqbD4z7da4NQdLOyq+kDBdLwktT4sDOCG8mAj0Jh6iwTUzA1lUDG1m\n6VQ1sA5GDSk0T1xNBSsm2fOyg26iaZ6BB5iwdSF45ECeRqLS2BQTRRpZePCIOAq7\nx1yNDQzyBrOk/6dCROMTK4kCAwEAAQ==\n-----END PUBLIC KEY-----'
>>> key.publickey().exportKey(format="OpenSSH")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/site-packages/Crypto/PublicKey/RSA.py", line 352, in exportKey
    keystring = ''.join([ struct.pack(">I",len(kp))+kp for kp in keyparts])
  File "/usr/local/lib/python3.4/site-packages/Crypto/PublicKey/RSA.py", line 352, in <listcomp>
    keystring = ''.join([ struct.pack(">I",len(kp))+kp for kp in keyparts])
TypeError: can't concat bytes to str
```

Seems that in the case of:

```
keystring = ''.join([ struct.pack(">I",len(kp))+kp for kp in keyparts])
```

kp is a string so we cant concat it with the result of struck.pack() which is indeed a byte object.

**Comment by SergSlipushenko** [comment]
+1. Same issue
Python 3.4.0, pycrypto==2.6
Traceback (most recent call last):
  File "/home/sslypushenko/projects/refstack/refstack/tests/unit/test_validators.py", line 105, in test_validation_with_signature
    'X-Public-Key': key.publickey().exportKey('OpenSSH')
  File "/home/sslypushenko/projects/refstack/.tox/py34/lib/python3.4/site-packages/Crypto/PublicKey/RSA.py", line 352, in exportKey
    keystring = ''.join([ struct.pack(">I",len(kp))+kp for kp in keyparts])
  File "/home/sslypushenko/projects/refstack/.tox/py34/lib/python3.4/site-packages/Crypto/PublicKey/RSA.py", line 352, in <listcomp>
    keystring = ''.join([ struct.pack(">I",len(kp))+kp for kp in keyparts])
TypeError: can't concat bytes to str

**Comment by sloat** [comment]
Importing OpenSSH keys is also broken on 2.6.1:

    Traceback (most recent call last):
    File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/asyncio/events.py", line 119, in _run
        self._callback(*self._args)
    File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/asyncio/selector_events.py", line 589, in _read_ready
        self._protocol.data_received(data)
    File "server.py", line 19, in data_received
        self.handle_state(msg)
    File "server.py", line 47, in handle_state
        key = RSA.importKey(self.pubkey)
    File "/path-to-my-venv/site-packages/Crypto/PublicKey/RSA.py", line 675, in importKey
        e = bytes_to_long(keyparts[1])
    IndexError: list index out of range

**Comment by iktakahiro** [comment]
This issue will be fixed ver 2.7.1. see below.

https://github.com/dlitz/pycrypto/commit/ab25c6fe95ee92fac3187dcd90e0560ccacb084a

**Comment by galgalesh** [comment]
Any idea when this will be released?

**Comment by kushaldas** [comment]
Can we please get a release with this fix?

**Comment by mikez302** [comment]
I'm not sure. See this: https://github.com/dlitz/pycrypto/issues/173

**Comment by rim-odoo** [comment]
Hi guys, (cc @dlitz )

I'm landing here after getting the same issue:
```python
  File "/usr/lib/python3.6/site-packages/Crypto/PublicKey/RSA.py", line 352, in exportKey
    keystring = ''.join([ struct.pack(">I",len(kp))+kp for kp in keyparts])
  File "/usr/lib/python3.6/site-packages/Crypto/PublicKey/RSA.py", line 352, in <listcomp>
    keystring = ''.join([ struct.pack(">I",len(kp))+kp for kp in keyparts])
TypeError: can't concat str to bytes
```

Is it possible, either:
- to ship a new version (2.7 ?) in PyPi, since the actual one 2.6.1 is quite out of date
- to backport this fix https://github.com/dlitz/pycrypto/commit/ab25c6fe95ee92fac3187dcd90e0560ccacb084a
in PyCrypto 2.6.1 ?
- to mark this lib is as unmaintained?

Thanks a lot for your feedback, let me know if I can help

**Comment by rim-odoo** [comment]
Side question: should I move my project under https://github.com/Legrandin/pycryptodome that looks to be actively maintained?

**Comment by galgalesh** [comment]
Yes, move your project to pycryptodome. It is a drop-in replacement for pycrypto.

**Comment by rim-odoo** [comment]
@galgalesh Thank your for advice :) good to know there is a drop-in replacement lib!

In a future step, I will probably move to [cryptography](https://github.com/pyca/cryptography) since it is already a dependency of a dependency of my project and I don't do very much crypto actually.
